### ISSUE TITLE
Clear Multiple selection when changing directory

### ISSUE THREAD

**Issue by Sergio-Muriel** [mdibaiee/Hawk#10]
When changing to another directory, the multiple selection is not clear.

Steps to reproduce:
- go to first dir, and make a multiple selection
- skip the selection, and go to another directory
- make a multiple selection of 2 items, then press "delete".

It says: are you sure you want to delete 5 items?

**Comment by mdibaiee** [comment]
Fixed in 0018380, thanks for reporting.
