### ISSUE TITLE
Support zip/rar creation and extraction

### ISSUE THREAD

**Issue by floppyrom** [mdibaiee/Hawk#12]
Can you please add support for the common compression formats?

**Comment by mdibaiee** [comment]
@floppyrom Thanks for your suggestion, I already had this in mind, I'll try to take a look as soon as I get time to. I'm also working on FTP Browser, so it might take a while.

**Comment by floppyrom** [comment]
@mdibaiee Awesome! I want to thank you for creating such a useful and beautiful app :)

**Comment by mdibaiee** [comment]
@floppyrom: Thank you very much! I'm glad you found it helpful, I'm just trying to work on this issue, hopefully I can fix it until tomorrow, but I'll probably release it as a new version with a few other features, so it might take a little while.

**Comment by mdibaiee** [comment]
@floppyrom: I added this feature, would you like to volunteer to test this feature? You can get the latest zip from: [hawk-1.1.0](https://github.com/mdibaiee/Hawk/releases/tag/1.1.0)

Use these guide to install the application on your device:
[Connection a Firefox OS device to the desktop](https://developer.mozilla.org/en-US/Firefox_OS/Debugging/Connecting_a_Firefox_OS_device_to_the_desktop)
[WebIDE](https://developer.mozilla.org/en-US/docs/Tools/WebIDE)

**Comment by floppyrom** [comment]
Hi Mahdi

Already on it! :D

Thanks for the invite. I'll start testing and come back to you with my
feedback.

Mihai
