### ISSUE TITLE
Not browsing sdcard

### ISSUE THREAD

**Issue by ElPopi** [mdibaiee/Hawk#16]
I've installed on ZTE Open II (FxOS v1.3) and I can't browse SDcard nor extSDcard. If It's related to this: 

> Firefox OS 2.2 and up are supported. Sadly 2.0 and 1.3 miss a lot of ES6 functionalities as well as CSS3 features (flexbox, etc) which break our application.

I'll close the issue. 

![2016-02-23-18-43-31](https://cloud.githubusercontent.com/assets/13170791/13267806/ee409198-da5d-11e5-949d-b3023c67bf73.png)

**Comment by mdibaiee** [comment]
@ElPopi Yes, as far as I remember, this error is related to FxOS 1.3, I could write a polyfill to make sdcard API work on 2.2, but not lower version.

Sorry about that. :disappointed:
