### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by mdibaiee** [mdibaiee/Hawk#6]
Currently, the only ways to navigate back are swiping (which most people are unfamiliar with) and clicking on breadcrumb (which has usability issues such as small tap area, and people are unfamiliar with, again).

I'd like to have a back button but I'm not sure where to put it, any ideas appreciated @nt1m @Sergio-Muriel

**Comment by nt1m** [comment]
You could put a small up button on the left of the breadcrumbs, kinda like Windows Explorer's navigation bar. Not sure if it looks cluttered though.

**Comment by mdibaiee** [comment]
That's exactly what I thought, but there is a problem with that, because breadcrumb's tap area is small, and there is navigation drawer on top if, it's going to be annoying, I tested it.

**Comment by mamal72** [comment]
Well, you can put a ".." with a different folder icon (maybe a folder icon with an arrow on it) on top of files and directories list. I think it can be good and looks better than a small button before breadcrumb, Hm? :smiley:

**Comment by mdibaiee** [comment]
@mamal72 that's a good idea, too. But normal users are not familiar with that concept, I think. Your idea would work for geeks tough :grinning:

**Comment by mamal72** [comment]
That's why we should use a different icon on it. :smile: 
A folder icon with a round counter clockwise arrow can be a good hint for them.
And you can mention it in the tour too.

**Comment by mdibaiee** [comment]
Hmm, you're right, probably an icon would demonstrate how it's going to work. What do you think @nt1m ?

**Comment by mamal72** [comment]
You can also use something like "UP" instead of that ".." with an up arrow icon.
I think the worst part of this method is where user goes to other views. In the list view it looks good but in the tile or thumbnail view (which I think you may implement it) it doesn't look as good as list view. But it's still the best way in my opinion. We have no toolbar or anything like that.
You can also improve breadcrumb interface and give it more height. This way, you can have a good, usable breadcrumb, a back button before it and an addition toolbar space after breadcrumb which you can use it later to place stuff. But you'll lose the precious screen space.  :unamused: There's a lot of FFOS devices with small screens compared to other smartphones.

**Comment by mdibaiee** [comment]
I added a back button to breadcrumb for now, may you please test it on a real device to see if there are any issues with touching it, I tried to move the navigation drawer's touch area a little away from breadcrumb.  @nt1m

**Comment by nt1m** [comment]
@mdibaiee Works fine to me, one issue though, the back button doesn't get disabled when you're already in the top level dir.

**Comment by nt1m** [comment]
Also, I have no trouble touching the icon. It'd be nice to have some touch feedback (for all buttons) though.

**Comment by mdibaiee** [comment]
@nt1m Great, I'm going to work on a better visual for the back button

**Comment by nt1m** [comment]
"Also, I have no trouble touching the icon."
Actually, I can accidently hit the menu button when using my thumb

**Comment by mdibaiee** [comment]
@nt1m Do you think the touching UX is good enough to be released? Or is it too annoying, if so we have to change strategy, probably.

Another possible solution would be placing a back button in the bottom toolbar, probably moving the "view" button to drawer, with radio boxes just like the Filter section, what do you think?

**Comment by mdibaiee** [comment]
@jorrete Do you have any idea on this topic? I would love to hear from more people.

**Comment by jorrete** [comment]
Other option would be:
| (back)           Hawk          (google)(breadcrumb)|

Hawk is centered and whenever you need back button you set visible the back arrow.

**Comment by mdibaiee** [comment]
I changed the breadcrumb's style as suggested by @mamal72, I think I'm going with the plan to put back button in the bottom toolbar and move views to navigation drawer, seems to be our best bet right now.

<img width="318" alt="screen shot 1394-07-05 at 18 43 06" src="https://cloud.githubusercontent.com/assets/2807772/10123481/7b6653e6-6547-11e5-8813-a6d58e3459f6.png">

**Comment by mamal72** [comment]
> I changed the breadcrumb's style as suggested by @mamal72

Looks so good to me. I wish I could test it but I've no device to test. :unamused:

**Comment by mdibaiee** [comment]
This is how it looks now: 
<img width="319" alt="screen shot 1394-07-06 at 16 34 32" src="https://cloud.githubusercontent.com/assets/2807772/10142067/2f8f9618-661d-11e5-9890-0de26195e1d1.png">
